/* V-Checker Wissensbasis – Quelle: Zutaten.txt
 *
 * status:
 *   "vegan"          – pflanzlich/mikrobiell, unbedenklich
 *   "vegetarian"     – tierisch ohne Schlachtung (Milch, Ei, Honig, Bienenwachs, Schellack)
 *   "non-vegetarian" – „nein" – tierisch vom toten Tier (Gelatine, Karmin, Fleisch, Fisch …)
 *   "conditional"    – „nicht sicher" – kann pflanzlich oder tierisch sein
 *
 * Hinweis: Vegane Einträge werden in der Analyse nicht als Treffer angezeigt – sie sind
 * trotzdem aufgeführt, um die Datenbasis vollständig nachvollziehbar zu halten.
 */

window.V_CHECK_DATA = {
  /* ════════════════════════  E-NUMMERN  ════════════════════════ */
  eNumbers: {
    // ── Farbstoffe (E100–E180) ──
    "E100":  { name: "Curcumin", status: "vegan" },
    "E101":  { name: "Riboflavin", status: "conditional", note: "kann mikrobiell/synthetisch oder aus Milch/Ei sein" },
    "E102":  { name: "Tartrazin", status: "vegan" },
    "E104":  { name: "Chinolingelb", status: "vegan" },
    "E110":  { name: "Gelborange S", status: "vegan" },
    "E120":  { name: "Karmin / Cochenille", status: "non-vegetarian", note: "aus Schildläusen" },
    "E122":  { name: "Azorubin", status: "vegan" },
    "E123":  { name: "Amaranth", status: "vegan" },
    "E124":  { name: "Cochenillerot A", status: "vegan", note: "trotz Name synthetisch" },
    "E127":  { name: "Erythrosin", status: "vegan" },
    "E129":  { name: "Allurarot AC", status: "vegan" },
    "E131":  { name: "Patentblau V", status: "vegan" },
    "E132":  { name: "Indigotin", status: "vegan" },
    "E133":  { name: "Brillantblau FCF", status: "vegan" },
    "E140":  { name: "Chlorophylle", status: "vegan" },
    "E141":  { name: "Kupferkomplexe der Chlorophylle", status: "vegan" },
    "E142":  { name: "Grün S", status: "vegan" },
    "E150a": { name: "Einfaches Zuckerkulör", status: "vegan" },
    "E150b": { name: "Sulfitlaugen-Zuckerkulör", status: "vegan" },
    "E150c": { name: "Ammoniak-Zuckerkulör", status: "vegan" },
    "E150d": { name: "Ammoniumsulfit-Zuckerkulör", status: "vegan" },
    "E151":  { name: "Brillantschwarz BN", status: "vegan" },
    "E153":  { name: "Pflanzenkohle", status: "vegan" },
    "E155":  { name: "Braun HT", status: "vegan" },
    "E160a": { name: "Carotine", status: "vegan" },
    "E160b": { name: "Annatto", status: "vegan" },
    "E160c": { name: "Paprikaextrakt", status: "vegan" },
    "E160d": { name: "Lycopin", status: "vegan" },
    "E160e": { name: "Beta-apo-8-Carotinal", status: "vegan" },
    "E161b": { name: "Lutein", status: "vegan" },
    "E161g": { name: "Canthaxanthin", status: "conditional", note: "synthetisch oder tier-/mikrobiell möglich" },
    "E162":  { name: "Betanin", status: "vegan" },
    "E163":  { name: "Anthocyane", status: "vegan" },
    "E170":  { name: "Calciumcarbonat", status: "vegan" },
    "E171":  { name: "Titandioxid", status: "vegan", note: "In der EU als Lebensmittelzusatzstoff seit 2022 verboten – auf Verpackungen aus Drittländern aber noch möglich; vegan" },
    "E172":  { name: "Eisenoxide", status: "vegan" },
    "E173":  { name: "Aluminium", status: "vegan" },
    "E174":  { name: "Silber", status: "vegan" },
    "E175":  { name: "Gold", status: "vegan" },
    "E180":  { name: "Litholrubin BK", status: "vegan" },

    // ── Konservierungsstoffe & Antioxidantien (E200–E392) ──
    "E200":  { name: "Sorbinsäure", status: "vegan" },
    "E202":  { name: "Kaliumsorbat", status: "vegan" },
    "E203":  { name: "Calciumsorbat", status: "vegan", note: "in der EU als Lebensmittelzusatzstoff nicht mehr zugelassen" },
    "E210":  { name: "Benzoesäure", status: "vegan" },
    "E211":  { name: "Natriumbenzoat", status: "vegan" },
    "E212":  { name: "Kaliumbenzoat", status: "vegan" },
    "E213":  { name: "Calciumbenzoat", status: "vegan" },
    "E214":  { name: "Ethyl-4-hydroxybenzoat", status: "vegan" },
    "E215":  { name: "Natriumethyl-4-hydroxybenzoat", status: "vegan" },
    "E218":  { name: "Methyl-4-hydroxybenzoat", status: "vegan" },
    "E219":  { name: "Natriummethyl-4-hydroxybenzoat", status: "vegan" },
    "E220":  { name: "Schwefeldioxid", status: "vegan" },
    "E221":  { name: "Natriumsulfit", status: "vegan" },
    "E222":  { name: "Natriumhydrogensulfit", status: "vegan" },
    "E223":  { name: "Natriummetabisulfit", status: "vegan" },
    "E224":  { name: "Kaliummetabisulfit", status: "vegan" },
    "E226":  { name: "Calciumsulfit", status: "vegan" },
    "E227":  { name: "Calciumhydrogensulfit", status: "vegan" },
    "E228":  { name: "Kaliumhydrogensulfit", status: "vegan" },
    "E234":  { name: "Nisin", status: "conditional", note: "durch Bakterien hergestellt, Kulturmedium prüfen" },
    "E235":  { name: "Natamycin", status: "vegan" },
    "E239":  { name: "Hexamethylentetramin", status: "vegan" },
    "E242":  { name: "Dimethyldicarbonat", status: "vegan" },
    "E249":  { name: "Kaliumnitrit", status: "vegan" },
    "E250":  { name: "Natriumnitrit", status: "vegan" },
    "E251":  { name: "Natriumnitrat", status: "vegan" },
    "E252":  { name: "Kaliumnitrat", status: "vegan" },
    "E260":  { name: "Essigsäure", status: "vegan" },
    "E261":  { name: "Kaliumacetat", status: "vegan" },
    "E262":  { name: "Natriumacetate", status: "vegan" },
    "E263":  { name: "Calciumacetat", status: "vegan" },
    "E270":  { name: "Milchsäure", status: "vegan", note: "trotz Name pflanzlich/mikrobiell" },
    "E280":  { name: "Propionsäure", status: "vegan" },
    "E281":  { name: "Natriumpropionat", status: "vegan" },
    "E282":  { name: "Calciumpropionat", status: "vegan" },
    "E283":  { name: "Kaliumpropionat", status: "vegan" },
    "E290":  { name: "Kohlendioxid", status: "vegan" },
    "E296":  { name: "Äpfelsäure", status: "vegan" },
    "E297":  { name: "Fumarsäure", status: "vegan" },
    "E300":  { name: "Ascorbinsäure", status: "vegan" },
    "E301":  { name: "Natriumascorbat", status: "vegan" },
    "E302":  { name: "Calciumascorbat", status: "vegan" },
    "E304":  { name: "Fettsäureester der Ascorbinsäure", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E306":  { name: "Tocopherolreiche Extrakte", status: "conditional", note: "meist pflanzlich, Träger prüfen" },
    "E307":  { name: "Alpha-Tocopherol", status: "conditional", note: "meist synthetisch/pflanzlich" },
    "E308":  { name: "Gamma-Tocopherol", status: "conditional", note: "meist synthetisch/pflanzlich" },
    "E309":  { name: "Delta-Tocopherol", status: "conditional", note: "meist synthetisch/pflanzlich" },
    "E310":  { name: "Propylgallat", status: "vegan" },
    "E311":  { name: "Octylgallat", status: "vegan" },
    "E312":  { name: "Dodecylgallat", status: "vegan" },
    "E315":  { name: "Isoascorbinsäure", status: "vegan" },
    "E316":  { name: "Natriumisoascorbat", status: "vegan" },
    "E319":  { name: "TBHQ", status: "vegan" },
    "E320":  { name: "BHA", status: "vegan" },
    "E321":  { name: "BHT", status: "vegan" },
    "E322":  { name: "Lecithine", status: "conditional", note: "Soja/Sonnenblume oder Ei möglich" },
    "E325":  { name: "Natriumlactat", status: "vegan" },
    "E326":  { name: "Kaliumlactat", status: "vegan" },
    "E327":  { name: "Calciumlactat", status: "vegan" },
    "E330":  { name: "Citronensäure", status: "vegan" },
    "E331":  { name: "Natriumcitrate", status: "vegan" },
    "E332":  { name: "Kaliumcitrate", status: "vegan" },
    "E333":  { name: "Calciumcitrate", status: "vegan" },
    "E334":  { name: "Weinsäure", status: "vegan" },
    "E335":  { name: "Natriumtartrate", status: "vegan" },
    "E336":  { name: "Kaliumtartrate", status: "vegan" },
    "E337":  { name: "Natriumkaliumtartrat", status: "vegan" },
    "E338":  { name: "Phosphorsäure", status: "vegan" },
    "E339":  { name: "Natriumphosphate", status: "vegan" },
    "E340":  { name: "Kaliumphosphate", status: "vegan" },
    "E341":  { name: "Calciumphosphate", status: "vegan" },
    "E343":  { name: "Magnesiumphosphate", status: "vegan" },
    "E350":  { name: "Natriummalate", status: "vegan" },
    "E351":  { name: "Kaliummalat", status: "vegan" },
    "E352":  { name: "Calciummalate", status: "vegan" },
    "E353":  { name: "Metaweinsäure", status: "vegan" },
    "E354":  { name: "Calciumtartrat", status: "vegan" },
    "E355":  { name: "Adipinsäure", status: "vegan" },
    "E356":  { name: "Natriumadipat", status: "vegan" },
    "E357":  { name: "Kaliumadipat", status: "vegan" },
    "E363":  { name: "Bernsteinsäure", status: "vegan" },
    "E380":  { name: "Triammoniumcitrat", status: "vegan" },
    "E385":  { name: "Calciumdinatrium-EDTA", status: "vegan" },
    "E392":  { name: "Rosmarinextrakt", status: "vegan" },

    // ── Verdickungsmittel & Emulgatoren (E400–E495) ──
    "E400":  { name: "Alginsäure", status: "vegan" },
    "E401":  { name: "Natriumalginat", status: "vegan" },
    "E402":  { name: "Kaliumalginat", status: "vegan" },
    "E403":  { name: "Ammoniumalginat", status: "vegan" },
    "E404":  { name: "Calciumalginat", status: "vegan" },
    "E405":  { name: "Propylenglycolalginat", status: "vegan" },
    "E406":  { name: "Agar", status: "vegan" },
    "E407":  { name: "Carrageen", status: "vegan" },
    "E407a": { name: "Eucheuma-Algen", status: "vegan" },
    "E410":  { name: "Johannisbrotkernmehl", status: "vegan" },
    "E412":  { name: "Guarkernmehl", status: "vegan" },
    "E413":  { name: "Traganth", status: "vegan" },
    "E414":  { name: "Gummi arabicum", status: "vegan" },
    "E415":  { name: "Xanthan", status: "vegan" },
    "E416":  { name: "Karaya-Gummi", status: "vegan" },
    "E417":  { name: "Tara-Gummi", status: "vegan" },
    "E418":  { name: "Gellan", status: "vegan" },
    "E422":  { name: "Glycerin", status: "conditional", note: "pflanzlich, synthetisch oder tierisch möglich" },
    "E423":  { name: "Modifiziertes Gummi arabicum", status: "vegan" },
    "E425":  { name: "Konjak", status: "vegan" },
    "E426":  { name: "Sojabohnen-Hemicellulose", status: "vegan" },
    "E427":  { name: "Cassia-Gummi", status: "vegan" },
    "E431":  { name: "Polyoxyethylenstearate", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E432":  { name: "Polysorbat 20", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E433":  { name: "Polysorbat 80", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E434":  { name: "Polysorbat 40", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E435":  { name: "Polysorbat 60", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E436":  { name: "Polysorbat 65", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E440":  { name: "Pektine", status: "vegan" },
    "E441":  { name: "Gelatine", status: "non-vegetarian", note: "tierischen Ursprungs" },
    "E442":  { name: "Ammoniumphosphatide", status: "conditional", note: "Fett-/Glycerinherkunft prüfen" },
    "E444":  { name: "Saccharoseacetatisobutyrat", status: "vegan" },
    "E445":  { name: "Glycerinester aus Wurzelharz", status: "conditional", note: "Glycerinherkunft prüfen" },
    "E460":  { name: "Cellulose", status: "vegan" },
    "E461":  { name: "Methylcellulose", status: "vegan" },
    "E462":  { name: "Ethylcellulose", status: "vegan" },
    "E463":  { name: "Hydroxypropylcellulose", status: "vegan" },
    "E464":  { name: "Hydroxypropylmethylcellulose", status: "vegan" },
    "E465":  { name: "Ethylmethylcellulose", status: "vegan" },
    "E466":  { name: "Carboxymethylcellulose", status: "vegan" },
    "E468":  { name: "Vernetzte Natriumcarboxymethylcellulose", status: "vegan" },
    "E469":  { name: "Hydrolysierte Carboxymethylcellulose", status: "vegan" },
    "E470a": { name: "Fettsäuresalze", status: "conditional", note: "pflanzlich oder tierisch möglich" },
    "E470b": { name: "Magnesiumsalze von Fettsäuren", status: "conditional", note: "pflanzlich oder tierisch möglich" },
    "E471":  { name: "Mono- und Diglyceride von Speisefettsäuren", status: "conditional", note: "pflanzlich oder tierisch möglich" },
    "E472a": { name: "Essigsäureester von Mono-/Diglyceriden", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E472b": { name: "Milchsäureester von Mono-/Diglyceriden", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E472c": { name: "Citronensäureester von Mono-/Diglyceriden", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E472d": { name: "Weinsäureester von Mono-/Diglyceriden", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E472e": { name: "DATEM", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E472f": { name: "Gemischte Ester", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E473":  { name: "Zuckerester von Speisefettsäuren", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E474":  { name: "Zuckerglyceride", status: "conditional", note: "Fettsäure-/Glycerinherkunft prüfen" },
    "E475":  { name: "Polyglycerinester", status: "conditional", note: "Fettsäure-/Glycerinherkunft prüfen" },
    "E476":  { name: "Polyglycerin-Polyricinoleat", status: "conditional", note: "meist pflanzlich, Glycerin prüfen" },
    "E477":  { name: "Propylenglycolester von Fettsäuren", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E479b": { name: "Oxidiertes Sojaöl mit Mono-/Diglyceriden", status: "conditional", note: "Mono-/Diglyceride prüfen" },
    "E481":  { name: "Natriumstearoyl-2-lactylat", status: "conditional", note: "Stearinsäureherkunft prüfen" },
    "E482":  { name: "Calciumstearoyl-2-lactylat", status: "conditional", note: "Stearinsäureherkunft prüfen" },
    "E483":  { name: "Stearyltartrat", status: "conditional", note: "Stearinsäureherkunft prüfen" },
    "E491":  { name: "Sorbitanmonostearat", status: "conditional", note: "Stearinsäureherkunft prüfen" },
    "E492":  { name: "Sorbitantristearat", status: "conditional", note: "Stearinsäureherkunft prüfen" },
    "E493":  { name: "Sorbitanmonolaurat", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E494":  { name: "Sorbitanmonooleat", status: "conditional", note: "Fettsäureherkunft prüfen" },
    "E495":  { name: "Sorbitanmonopalmitat", status: "conditional", note: "Fettsäureherkunft prüfen" },

    // ── Mineralstoffe / pH-Regulatoren (E500–E585) ──
    "E500":  { name: "Natriumcarbonate", status: "vegan" },
    "E501":  { name: "Kaliumcarbonate", status: "vegan" },
    "E503":  { name: "Ammoniumcarbonate", status: "vegan" },
    "E504":  { name: "Magnesiumcarbonate", status: "vegan" },
    "E507":  { name: "Salzsäure", status: "vegan" },
    "E508":  { name: "Kaliumchlorid", status: "vegan" },
    "E509":  { name: "Calciumchlorid", status: "vegan" },
    "E511":  { name: "Magnesiumchlorid", status: "vegan" },
    "E512":  { name: "Zinnchlorid", status: "vegan" },
    "E514":  { name: "Natriumsulfate", status: "vegan" },
    "E515":  { name: "Kaliumsulfate", status: "vegan" },
    "E516":  { name: "Calciumsulfat", status: "vegan" },
    "E517":  { name: "Ammoniumsulfat", status: "vegan" },
    "E520":  { name: "Aluminiumsulfat", status: "vegan" },
    "E521":  { name: "Aluminium-Natriumsulfat", status: "vegan" },
    "E522":  { name: "Aluminium-Kaliumsulfat", status: "vegan" },
    "E523":  { name: "Aluminium-Ammoniumsulfat", status: "vegan" },
    "E524":  { name: "Natriumhydroxid", status: "vegan" },
    "E525":  { name: "Kaliumhydroxid", status: "vegan" },
    "E526":  { name: "Calciumhydroxid", status: "vegan" },
    "E527":  { name: "Ammoniumhydroxid", status: "vegan" },
    "E528":  { name: "Magnesiumhydroxid", status: "vegan" },
    "E529":  { name: "Calciumoxid", status: "vegan" },
    "E530":  { name: "Magnesiumoxid", status: "vegan" },
    "E535":  { name: "Natriumferrocyanid", status: "vegan" },
    "E536":  { name: "Kaliumferrocyanid", status: "vegan" },
    "E538":  { name: "Calciumferrocyanid", status: "vegan" },
    "E542":  { name: "Knochenphosphat", status: "non-vegetarian", note: "aus Tierknochen gewonnen" },
    "E551":  { name: "Siliciumdioxid", status: "vegan" },
    "E552":  { name: "Calciumsilicat", status: "vegan" },
    "E553a": { name: "Magnesiumsilicate", status: "vegan" },
    "E553b": { name: "Talkum", status: "vegan" },
    "E554":  { name: "Natriumaluminiumsilicat", status: "vegan" },
    "E555":  { name: "Kaliumaluminiumsilicat", status: "vegan" },
    "E556":  { name: "Calciumaluminiumsilicat", status: "vegan" },
    "E558":  { name: "Bentonit", status: "vegan" },
    "E559":  { name: "Aluminiumsilicat", status: "vegan" },
    "E570":  { name: "Fettsäuren", status: "conditional", note: "pflanzlich oder tierisch möglich" },
    "E574":  { name: "Gluconsäure", status: "vegan" },
    "E575":  { name: "Glucono-delta-lacton", status: "vegan" },
    "E576":  { name: "Natriumgluconat", status: "vegan" },
    "E577":  { name: "Kaliumgluconat", status: "vegan" },
    "E578":  { name: "Calciumgluconat", status: "vegan" },
    "E579":  { name: "Eisengluconat", status: "vegan" },
    "E585":  { name: "Eisenlactat", status: "vegan" },

    // ── Geschmacksverstärker (E620–E650) ──
    "E620":  { name: "Glutaminsäure", status: "vegan" },
    "E621":  { name: "Mononatriumglutamat", status: "vegan" },
    "E622":  { name: "Monokaliumglutamat", status: "vegan" },
    "E623":  { name: "Calciumdiglutamat", status: "vegan" },
    "E624":  { name: "Monoammoniumglutamat", status: "vegan" },
    "E625":  { name: "Magnesiumdiglutamat", status: "vegan" },
    "E626":  { name: "Guanylsäure", status: "conditional", note: "kann aus Hefe/Fisch/Fleisch stammen" },
    "E627":  { name: "Dinatriumguanylat", status: "conditional", note: "kann aus Hefe/Fisch/Fleisch stammen" },
    "E628":  { name: "Dikaliumguanylat", status: "conditional", note: "kann aus Hefe/Fisch/Fleisch stammen" },
    "E629":  { name: "Calciumguanylat", status: "conditional", note: "kann aus Hefe/Fisch/Fleisch stammen" },
    "E630":  { name: "Inosinsäure", status: "conditional", note: "kann aus Fleisch/Fisch oder Fermentation stammen" },
    "E631":  { name: "Dinatriuminosinat", status: "conditional", note: "kann aus Fleisch/Fisch oder Fermentation stammen" },
    "E632":  { name: "Dikaliuminosinat", status: "conditional", note: "kann aus Fleisch/Fisch oder Fermentation stammen" },
    "E633":  { name: "Calciuminosinat", status: "conditional", note: "kann aus Fleisch/Fisch oder Fermentation stammen" },
    "E634":  { name: "Calcium-5-ribonucleotide", status: "conditional", note: "Herkunft prüfen" },
    "E635":  { name: "Dinatrium-5-ribonucleotide", status: "conditional", note: "Herkunft prüfen" },
    "E640":  { name: "Glycin und Natriumsalz", status: "conditional", note: "synthetisch oder tierisch möglich" },
    "E650":  { name: "Zinkacetat", status: "vegan" },

    // ── Wachse, Glasurmittel (E901–E914) ──
    "E901":  { name: "Bienenwachs", status: "vegetarian", note: "Bienenprodukt – nicht vegan" },
    "E902":  { name: "Candelillawachs", status: "vegan" },
    "E903":  { name: "Carnaubawachs", status: "vegan" },
    "E904":  { name: "Schellack", status: "conditional", note: "aus Lackschildlaus – von vielen Vegetarierstandards ausgeschlossen (V-Label, Vegetarian Society)" },
    "E905":  { name: "Mikrokristallines Wachs", status: "vegan" },
    "E907":  { name: "Hydriertes Poly-1-decen", status: "vegan" },
    "E912":  { name: "Montansäureester", status: "vegan" },
    "E914":  { name: "Oxidiertes Polyethylenwachs", status: "vegan" },

    // ── Aminosäuren / Sonstige (E920–E949) ──
    "E920":  { name: "L-Cystein", status: "conditional", note: "synthetisch, mikrobiell oder tierisch möglich" },
    "E927b": { name: "Carbamid", status: "vegan" },
    "E938":  { name: "Argon", status: "vegan" },
    "E939":  { name: "Helium", status: "vegan" },
    "E941":  { name: "Stickstoff", status: "vegan" },
    "E942":  { name: "Distickstoffmonoxid", status: "vegan" },
    "E943a": { name: "Butan", status: "vegan" },
    "E943b": { name: "Isobutan", status: "vegan" },
    "E944":  { name: "Propan", status: "vegan" },
    "E948":  { name: "Sauerstoff", status: "vegan" },
    "E949":  { name: "Wasserstoff", status: "vegan" },

    // ── Süßstoffe (E950–E969) ──
    "E950":  { name: "Acesulfam K", status: "vegan" },
    "E951":  { name: "Aspartam", status: "vegan" },
    "E952":  { name: "Cyclamate", status: "vegan" },
    "E954":  { name: "Saccharin", status: "vegan" },
    "E955":  { name: "Sucralose", status: "vegan" },
    "E957":  { name: "Thaumatin", status: "vegan" },
    "E959":  { name: "Neohesperidin DC", status: "vegan" },
    "E960":  { name: "Steviolglycoside", status: "vegan" },
    "E961":  { name: "Neotam", status: "vegan" },
    "E962":  { name: "Aspartam-Acesulfamsalz", status: "vegan" },
    "E964":  { name: "Polyglycitolsirup", status: "vegan" },
    "E965":  { name: "Maltit / Maltitsirup", status: "vegan" },
    "E966":  { name: "Lactit", status: "vegetarian", note: "aus Milchzucker (Lactose) hergestellt – vegetarisch, nicht vegan" },
    "E967":  { name: "Xylit", status: "vegan" },
    "E968":  { name: "Erythrit", status: "vegan" },
    "E969":  { name: "Advantam", status: "vegan" },

    // ── E999 und Folgenummern ──
    "E999":  { name: "Quillajaextrakt", status: "vegan" },
    "E1103": { name: "Invertase", status: "conditional", note: "Enzymherkunft/Träger prüfen" },
    "E1105": { name: "Lysozym", status: "vegetarian", note: "meist aus Ei – nicht vegan" },
    "E1200": { name: "Polydextrose", status: "vegan" },
    "E1201": { name: "Polyvinylpyrrolidon", status: "vegan" },
    "E1202": { name: "Polyvinylpolypyrrolidon", status: "vegan" },
    "E1203": { name: "Polyvinylalkohol", status: "vegan" },
    "E1204": { name: "Pullulan", status: "vegan" },
    "E1205": { name: "Basisches Methacrylat-Copolymer", status: "vegan" },
    "E1206": { name: "Neutrales Methacrylat-Copolymer", status: "vegan" },
    "E1207": { name: "Anionisches Methacrylat-Copolymer", status: "vegan" },
    "E1208": { name: "Polyvinylpyrrolidon-Vinylacetat-Copolymer", status: "vegan" },
    "E1209": { name: "Polyvinylalkohol-Polyethylenglycol-Graft-Copolymer", status: "vegan" },
    "E1404": { name: "Oxidierte Stärke", status: "vegan" },
    "E1410": { name: "Monostärkephosphat", status: "vegan" },
    "E1412": { name: "Distärkephosphat", status: "vegan" },
    "E1413": { name: "Phosphatiertes Distärkephosphat", status: "vegan" },
    "E1414": { name: "Acetyliertes Distärkephosphat", status: "vegan" },
    "E1420": { name: "Acetylierte Stärke", status: "vegan" },
    "E1422": { name: "Acetyliertes Distärkeadipat", status: "vegan" },
    "E1440": { name: "Hydroxypropylstärke", status: "vegan" },
    "E1442": { name: "Hydroxypropyldistärkephosphat", status: "vegan" },
    "E1450": { name: "Stärkenatriumoctenylsuccinat", status: "vegan" },
    "E1451": { name: "Acetylierte oxidierte Stärke", status: "vegan" },
    "E1452": { name: "Stärkealuminiumoctenylsuccinat", status: "vegan" },
    "E1505": { name: "Triethylcitrat", status: "vegan" },
    "E1517": { name: "Glyceryldiacetat", status: "conditional", note: "Glycerinherkunft prüfen" },
    "E1518": { name: "Glyceryltriacetat", status: "conditional", note: "Glycerinherkunft prüfen" },
    "E1520": { name: "Propylenglycol", status: "vegan" },
    "E1521": { name: "Polyethylenglycol", status: "vegan" },
  },

  /* ════════════════════════  KLARTEXT-ZUTATEN  ════════════════════════
   * Jeder Eintrag:
   *   terms:    Substring-Suchmuster (lowercase)
   *   exclude:  Substrings, bei deren Vorkommen das Match ignoriert wird
   *             (für Komposita wie „Sojamilch" → „Milch" nicht triggern)
   */
  keywords: [
    /* === NOT VEGETARIAN === */
    {
      status: "conditional",
      label: "Albumin",
      reason: "Origin unclear: may be egg (vegetarian) or blood (not vegetarian). Check with manufacturer.",
      terms: ["albumin"],
      termsEn: ["albumin", "blood albumin"],
      termsFr: ["albumine", "albumine sanguine"],
      termsIt: ["albumina", "albumina del sangue"],
      termsEs: ["albumina", "albumina de sangre"],
      exclude: ["lactalbumin", "laktalbumin", "ovalbumin", "eieralbumin", "milchalbumin", "molkenalbumin", "sojaalbumin", "pflanzliches albumin", "lactalbumine", "ovoalbumina", "ovoalbumina", "egg albumin", "milk albumin", "soy albumin", "plant albumin"]
    },
    {
      status: "non-vegetarian",
      label: "Anchovies / Sardines",
      reason: "Fish.",
      terms: ["anchovis", "ankovis", "sardelle", "sardellen"],
      termsEn: ["anchovy", "anchovies", "sardine", "sardines"],
      termsFr: ["anchois", "sardine", "sardines"],
      termsIt: ["acciuga", "acciughe", "alice", "sardina", "sardine"],
      termsEs: ["anchoa", "anchoas", "boqueron", "boquerones", "sardina", "sardinas"]
    },
    {
      status: "non-vegetarian",
      label: "Aspic / Jelly",
      reason: "Usually animal gelatin or meat broth.",
      terms: ["aspik", "sulze", "sulz"],
      termsEn: ["aspic"],
      termsFr: ["aspic", "gelee de viande"],
      termsIt: ["aspic", "gelatina di carne"],
      termsEs: ["aspic", "gelatina de carne"]
    },
    {
      status: "non-vegetarian",
      label: "Chitosan",
      reason: "Usually derived from crustacean shells.",
      terms: ["chitosan"],
      termsEn: ["chitosan"],
      termsFr: ["chitosane", "chitosan"],
      termsIt: ["chitosano"],
      termsEs: ["quitosano", "chitosan"]
    },
    {
      status: "non-vegetarian",
      label: "Cholesterol",
      reason: "Animal-derived.",
      terms: ["cholesterin", "cholesterol"],
      termsEn: ["cholesterol"],
      termsFr: ["cholesterol"],
      termsIt: ["colesterolo"],
      termsEs: ["colesterol"]
    },
    {
      status: "non-vegetarian",
      label: "Carmine / Cochineal",
      reason: "Red dye from crushed scale insects (E120).",
      terms: ["karmin", "carmin", "carminsaure", "karminsaure", "cochenille", "cochineal"],
      termsEn: ["carmine", "cochineal", "carminic acid", "natural red 4", "crimson lake"],
      termsFr: ["carmin", "cochenille", "acide carminique"],
      termsIt: ["carminio", "cocciniglia", "acido carminico"],
      termsEs: ["carmin", "cochinilla", "acido carminico"],
      exclude: ["cochenillerot a", "ponceau"]
    },
    {
      status: "non-vegetarian",
      label: "Collagen",
      reason: "From animal connective tissue.",
      terms: ["collagen", "kollagen"],
      termsEn: ["collagen"],
      termsFr: ["collagene"],
      termsIt: ["collagene"],
      termsEs: ["colageno"]
    },
    {
      status: "non-vegetarian",
      label: "Dashi",
      reason: "Usually fish-based (except pure kombu dashi).",
      terms: ["dashi"],
      termsEn: ["dashi", "bonito flakes", "katsuobushi", "fish dashi"],
      termsFr: ["dashi"],
      termsIt: ["dashi"],
      termsEs: ["dashi"],
      exclude: ["kombu-dashi", "kombu dashi", "kombu broth"]
    },
    {
      status: "non-vegetarian",
      label: "Fish oil",
      reason: "From fish.",
      terms: ["fischol", "fischoel"],
      termsEn: ["fish oil", "cod liver oil", "omega-3 fish oil"],
      termsFr: ["huile de poisson", "huile de foie de morue"],
      termsIt: ["olio di pesce", "olio di fegato di merluzzo"],
      termsEs: ["aceite de pescado", "aceite de higado de bacalao"]
    },
    {
      status: "non-vegetarian",
      label: "Fish sauce",
      reason: "From fish.",
      terms: ["fischsauce", "fish sauce", "nuoc mam", "nam pla"],
      termsEn: ["fish sauce", "nam pla", "nuoc mam", "oyster sauce"],
      termsFr: ["sauce de poisson", "nuoc-mam"],
      termsIt: ["salsa di pesce", "colatura di alici"],
      termsEs: ["salsa de pescado", "nam pla"]
    },
    {
      status: "non-vegetarian",
      label: "Gelatin",
      reason: "Animal collagen from bones or hides (pork or beef).",
      terms: ["gelatine", "gelatin", "speisegelatine", "schweinegelatine", "rindergelatine", "kalbergelatine", "fischgelatine"],
      termsEn: ["gelatin", "gelatine", "pork gelatin", "beef gelatin", "fish gelatin", "bovine gelatin"],
      termsFr: ["gelatine", "gelatine de porc", "gelatine de boeuf", "gelatine de poisson"],
      termsIt: ["gelatina", "gelatina di maiale", "gelatina di manzo", "gelatina di pesce"],
      termsEs: ["gelatina", "gelatina de cerdo", "gelatina de res", "gelatina de pescado"]
    },
    {
      status: "non-vegetarian",
      label: "Isinglass",
      reason: "Fish product used as fining agent.",
      terms: ["hausenblase", "isinglass"],
      termsEn: ["isinglass"],
      termsFr: ["colle de poisson"],
      termsIt: ["colla di pesce", "ittiocolla"],
      termsEs: ["cola de pescado", "ictiocola"]
    },
    {
      status: "non-vegetarian",
      label: "Keratin",
      reason: "From hair, feathers or hooves.",
      terms: ["keratin"],
      termsEn: ["keratin"],
      termsFr: ["keratine"],
      termsIt: ["cheratina"],
      termsEs: ["queratina"]
    },
    {
      status: "non-vegetarian",
      label: "Bone char / Bone meal",
      reason: "Processing aid from animal bones.",
      terms: ["knochenkohle", "knochenmehl"],
      termsEn: ["bone char", "bone charcoal", "bone meal"],
      termsFr: ["charbon d'os", "farine d'os"],
      termsIt: ["carbone d'ossa", "farina d'ossa"],
      termsEs: ["carbon de hueso", "harina de huesos"]
    },
    {
      status: "non-vegetarian",
      label: "Rennet (animal)",
      reason: "From calf or animal stomachs.",
      terms: ["kalberlab", "tierisches lab", "animalisches lab", "tierisches labferment", "naturliches lab", "lab tierisch"],
      termsEn: ["animal rennet", "calf rennet", "natural rennet"],
      termsFr: ["presure animale", "presure de veau"],
      termsIt: ["caglio animale", "caglio di vitello"],
      termsEs: ["cuajo animal", "cuajo de ternera"]
    },
    {
      status: "non-vegetarian",
      label: "Lard / Tallow",
      reason: "Animal fat.",
      terms: ["schmalz", "schweineschmalz", "schweinefett", "talg", "rindertalg", "speisetalg", "tierisches fett", "tierische fette"],
      termsEn: ["lard", "tallow", "beef tallow", "pork fat", "suet", "dripping", "animal fat"],
      termsFr: ["saindoux", "suif", "graisse animale", "graisse de porc", "graisse de boeuf"],
      termsIt: ["strutto", "sego", "grasso animale", "grasso di maiale", "grasso di manzo"],
      termsEs: ["manteca", "manteca de cerdo", "sebo", "grasa animal"],
      exclude: ["pflanzliches fett", "pflanzlicher talg", "vegetable fat", "plant fat", "matiere grasse vegetale"]
    },
    {
      status: "non-vegetarian",
      label: "Meat / Poultry",
      reason: "Contains meat or poultry.",
      terms: ["schweinefleisch", "rindfleisch", "kalbfleisch", "lammfleisch", "hahnchenfleisch", "huhnerfleisch", "putenfleisch", "truthahn", "entenfleisch", "gansefleisch", "wildfleisch", "wildschwein", "kaninchenfleisch", "pferdefleisch", "bacon", "speck", "schinken", "salami", "wurst", "wurstwaren", "mortadella", "leberwurst", "blutwurst", "bratwurst", "chorizo", "pancetta", "hackfleisch", "fleischextrakt"],
      termsEn: ["pork", "beef", "chicken", "turkey", "lamb", "veal", "duck", "goose", "mutton", "venison", "rabbit meat", "horse meat", "bacon", "ham", "salami", "sausage", "chorizo", "pepperoni", "prosciutto", "pancetta", "mortadella", "luncheon meat", "meat extract", "poultry", "minced meat", "ground beef", "ground pork"],
      termsFr: ["porc", "boeuf", "poulet", "dinde", "agneau", "veau", "canard", "oie", "mouton", "venaison", "lapin", "jambon", "bacon", "saucisson", "lardons", "chorizo", "mortadelle", "volaille", "viande hachee", "extrait de viande"],
      termsIt: ["maiale", "manzo", "pollo", "tacchino", "agnello", "vitello", "anatra", "oca", "montone", "cinghiale", "coniglio", "prosciutto", "pancetta", "salame", "mortadella", "salsiccia", "speck", "bresaola", "pollame", "carne macinata"],
      termsEs: ["cerdo", "ternera", "pollo", "pavo", "cordero", "pato", "oca", "caza", "jamon", "bacon", "salchichon", "chorizo", "mortadela", "panceta", "ave", "carne picada"],
      exclude: ["fleischlos", "vegetarische wurst", "vegane wurst", "ohne fleisch", "meatless", "vegan meat", "plant-based meat", "meat-free", "champignon", "chamomile", "chamomille", "chamomilla", "manzanilla"]
    },
    {
      status: "non-vegetarian",
      label: "Fish / Seafood",
      reason: "Contains fish or seafood.",
      terms: ["lachs", "thunfisch", "hering", "matjes", "makrele", "kabeljau", "scholle", "forelle", "garnele", "garnelen", "shrimp", "krabbe", "krabben", "hummer", "languste", "krebs", "krebse", "muschel", "muscheln", "auster", "austern", "tintenfisch", "calamari", "sepia", "kaviar", "rogen", "fischmehl", "fischbruhe", "fischfond"],
      termsEn: ["salmon", "tuna", "herring", "mackerel", "cod", "trout", "halibut", "sole", "shrimp", "prawns", "crab", "lobster", "crayfish", "mussel", "oyster", "squid", "octopus", "caviar", "roe", "fish meal", "fish protein", "fish stock", "fish broth"],
      termsFr: ["saumon", "thon", "hareng", "maquereau", "cabillaud", "truite", "crevette", "crabe", "homard", "ecrevisse", "moule", "huitre", "calmar", "poulpe", "caviar", "oeufs de poisson", "bouillon de poisson"],
      termsIt: ["salmone", "tonno", "aringa", "sgombro", "merluzzo", "trota", "halibut", "gamberetto", "gambero", "granchio", "aragosta", "astice", "cozza", "ostrica", "calamaro", "polpo", "caviale", "uova di pesce", "brodo di pesce"],
      termsEs: ["salmon", "atun", "arenque", "caballa", "bacalao", "trucha", "lenguado", "gamba", "langostino", "cangrejo", "langosta", "mejillon", "ostra", "calamar", "pulpo", "caviar", "huevas", "caldo de pescado"],
      exclude: ["fischfrei", "fish-free", "vegan fish sauce", "sans poisson", "senza pesce", "sin pescado"]
    },
    {
      status: "non-vegetarian",
      label: "Stock / Broth (animal)",
      reason: "Meat or bone broth.",
      terms: ["fleischbruhe", "rinderbruhe", "rinderfond", "geflugel bruhe", "huhnerbruhe", "huhnerfond", "knochenbruhe", "kalbsfond"],
      termsEn: ["chicken stock", "beef stock", "chicken broth", "beef broth", "bone broth", "veal stock", "meat extract", "chicken powder", "beef extract"],
      termsFr: ["bouillon de poulet", "bouillon de boeuf", "fond de volaille", "bouillon d'os", "fond de veau", "extrait de viande"],
      termsIt: ["brodo di pollo", "brodo di manzo", "brodo di ossa", "fondo di vitello", "estratto di carne"],
      termsEs: ["caldo de pollo", "caldo de ternera", "caldo de huesos", "extracto de carne", "caldo de carne"]
    },
    {
      status: "non-vegetarian",
      label: "Offal / Organ meat",
      reason: "Liver, kidney, bone marrow or other organ meat.",
      terms: ["leber ", "leber,", "niere", "kutteln", "bries", "knochenmark", "blutplasma"],
      termsEn: ["liver", "kidney", "tripe", "sweetbread", "bone marrow", "blood plasma"],
      termsFr: ["foie", "rognon", "tripes", "ris de veau", "moelle osseuse", "plasma sanguin"],
      termsIt: ["fegato", "rene", "trippa", "animelle", "midollo osseo", "plasma sanguigno"],
      termsEs: ["higado", "rinon", "callos", "mollejas", "tuetano", "plasma sanguineo"],
      exclude: ["leberkase-aroma", "leberblumchen", "liver-free"]
    },
    {
      status: "non-vegetarian",
      label: "Pepsin",
      reason: "Digestive enzyme from pig stomachs.",
      terms: ["pepsin"],
      termsEn: ["pepsin"],
      termsFr: ["pepsine"],
      termsIt: ["pepsina"],
      termsEs: ["pepsina"]
    },

    /* === VEGETARIAN (not vegan) === */
    {
      status: "vegetarian",
      label: "Milk / Dairy",
      reason: "Contains milk or milk derivatives (vegetarian, not vegan).",
      terms: ["milch", "vollmilch", "magermilch", "kondensmilch", "buttermilch", "milchpulver", "vollmilchpulver", "magermilchpulver", "milcheiweis", "milcherzeugnis", "milchfett", "milchzucker", "lactose", "laktose", "sussmolkenpulver"],
      termsEn: ["milk", "whole milk", "skimmed milk", "skim milk", "condensed milk", "buttermilk", "milk powder", "skimmed milk powder", "whole milk powder", "milk solids", "milk protein", "milk fat", "milkfat", "lactose", "dairy"],
      termsFr: ["lait", "lait entier", "lait ecreme", "lait concentre", "babeurre", "poudre de lait", "proteines de lait", "matieres grasses laitieres", "lactose", "produits laitiers"],
      termsIt: ["latte", "latte intero", "latte scremato", "latte condensato", "latticello", "polvere di latte", "proteine del latte", "grassi del latte", "lattosio", "derivati del latte"],
      termsEs: ["leche", "leche entera", "leche desnatada", "leche condensada", "suero de leche", "proteinas lacteas", "grasa lactea", "lactosa", "productos lacteos", "leche en polvo"],
      exclude: ["milchsaure", "milchsaurebakterien", "milchsaurekultur", "kokosmilch", "mandelmilch", "sojamilch", "hafermilch", "reismilch", "pflanzenmilch", "ohne milch", "milchfrei", "milchersatz", "coconut milk", "oat milk", "almond milk", "soy milk", "soya milk", "rice milk", "dairy-free", "milk-free", "lait de coco", "lait de soja", "lait d'avoine", "lait d'amande", "latte di cocco", "latte di soia", "latte di avena", "leche de coco", "leche de soja", "leche de avena", "laitue", "laiteron", "lactucarium"]
    },
    {
      status: "vegetarian",
      label: "Whey",
      reason: "Milk derivative - not vegan.",
      terms: ["molke", "molkenpulver", "molkeneiweiss", "molkenprotein", "whey", "suessmolke"],
      termsEn: ["whey", "whey powder", "whey protein", "whey concentrate", "whey isolate"],
      termsFr: ["lactoserum", "petit-lait", "proteines de lactoserum", "whey"],
      termsIt: ["siero di latte", "siero", "proteine del siero", "whey"],
      termsEs: ["suero de leche", "suero lacteo", "proteina de suero", "whey"]
    },
    {
      status: "vegetarian",
      label: "Casein / Caseinate",
      reason: "Milk protein - not vegan.",
      terms: ["casein", "kasein", "caseinat", "kaseinat", "natriumcaseinat", "calciumcaseinat"],
      termsEn: ["casein", "caseinate", "sodium caseinate", "calcium caseinate", "milk casein"],
      termsFr: ["caseine", "caseinate", "caseinate de sodium", "caseinate de calcium"],
      termsIt: ["caseina", "caseinato", "caseinato di sodio", "caseinato di calcio"],
      termsEs: ["caseina", "caseinato", "caseinato de sodio", "caseinato de calcio"]
    },
    {
      status: "vegetarian",
      label: "Butter / Cream",
      reason: "Animal milk fat.",
      terms: ["butter", "butterreinfett", "butterfett", "butterschmalz", "sahne", "schlagsahne", "susrahm", "sauerrahm", "rahm", "creme fraiche", "schmand", "ghee", "mascarpone"],
      termsEn: ["butter", "cream", "double cream", "single cream", "sour cream", "heavy cream", "whipping cream", "butterfat", "butter oil", "ghee", "clarified butter", "creme fraiche", "mascarpone", "clotted cream"],
      termsFr: ["beurre", "creme", "creme fraiche", "creme liquide", "creme epaisse", "ghee", "beurre clarifie", "mascarpone"],
      termsIt: ["burro", "panna", "panna fresca", "panna acida", "panna da montare", "ghee", "burro chiarificato", "mascarpone"],
      termsEs: ["mantequilla", "nata", "crema", "crema agria", "nata para montar", "ghee", "mantequilla clarificada", "mascarpone"],
      exclude: ["erdnussbutter", "kakaobutter", "sheabutter", "nussbutter", "mandelbutter", "kokosbutter", "pflanzenbutter", "vegane butter", "butterersatz", "buttersaure", "peanut butter", "cocoa butter", "shea butter", "nut butter", "almond butter", "cashew butter", "coconut butter", "vegan butter", "beurre de cacao", "burro di cacao", "mantequilla de cacahuete", "manteca de cacao", "coconut cream", "cream of tartar", "creme de tartre", "creamed coconut", "ice cream alternative", "vegan cream"]
    },
    {
      status: "conditional",
      label: "Cheese / Yogurt",
      reason: "Dairy products – yogurt is vegetarian; cheese may contain animal rennet. PDO cheeses (Parmesan, Parmigiano Reggiano, Grana Padano, Pecorino) traditionally use animal rennet.",
      terms: ["kase", "kaese", "joghurt", "yoghurt", "quark", "topfen", "skyr", "mozzarella", "parmesan", "parmigiano", "gouda", "cheddar", "feta", "ricotta", "frischkase", "huttenkase", "emmentaler", "edamer", "camembert", "brie", "gorgonzola", "halloumi", "raclette"],
      termsEn: ["cheese", "yogurt", "yoghurt", "quark", "fromage frais", "mozzarella", "parmesan", "parmesan reggiano", "parmigiano reggiano", "grana padano", "pecorino", "gouda", "cheddar", "feta", "ricotta", "cream cheese", "cottage cheese", "brie", "camembert", "emmental", "halloumi", "skyr"],
      termsFr: ["fromage", "yaourt", "fromage blanc", "quark", "mozzarella", "parmesan", "parmigiano reggiano", "grana padano", "pecorino", "gouda", "cheddar", "feta", "ricotta", "brie", "camembert", "emmental", "gruyere", "comte"],
      termsIt: ["formaggio", "yogurt", "yoghurt", "ricotta", "mozzarella", "parmigiano", "parmigiano reggiano", "grana padano", "pecorino", "fontina", "gorgonzola", "brie", "camembert", "asiago"],
      termsEs: ["queso", "yogur", "yoghurt", "requeson", "mozzarella", "parmesano", "parmigiano reggiano", "grana padano", "pecorino", "gouda", "cheddar", "feta", "brie", "camembert", "manchego", "queso fresco"],
      exclude: ["pflanzlicher kase", "veganer kase", "kaseersatz", "ohne kase", "joghurtalternative", "sojajoghurt", "kokosjoghurt", "haferjoghurt", "mandeljoghurt", "vegan cheese", "dairy-free cheese", "vegan yogurt", "soy yogurt", "coconut yogurt", "fromage vegetal", "yaourt vegetal", "formaggio vegano", "yogurt vegano", "queso vegano", "yogur vegano"]
    },
    {
      status: "vegetarian",
      label: "Egg / Egg products",
      reason: "Contains egg or egg derivatives (vegetarian, not vegan).",
      terms: ["huhnerei", "huehnerei", "vollei", "trockenei", "eipulver", "eigelb", "eidotter", "eiklar", "huhnereiweiss", "eier", "eieralbumin", "ovalbumin", "ovomucoid"],
      termsEn: ["egg", "eggs", "egg yolk", "egg white", "whole egg", "dried egg", "egg powder", "free-range egg", "ovalbumin", "ovomucoid", "egg albumen", "liquid egg", "egg solids"],
      termsFr: ["oeuf", "oeufs", "jaune d'oeuf", "blanc d'oeuf", "oeuf entier", "poudre d'oeuf", "ovalbumine"],
      termsIt: ["uovo", "uova", "tuorlo d'uovo", "albume d'uovo", "uovo intero", "uovo in polvere", "ovoalbumina", "ovomucoide"],
      termsEs: ["huevo", "huevos", "yema de huevo", "clara de huevo", "huevo entero", "huevo en polvo", "ovoalbumina"],
      exclude: ["eifrei", "veganes ei", "ei-ersatz", "egg-free", "vegan egg", "egg replacer", "sans oeuf", "senza uova", "sin huevo", "eggplant", "egg fruit", "egg nog", "freier", "freie", "freies", "freien", "freiem"]
    },
    {
      status: "vegetarian",
      label: "Honey",
      reason: "Bee product (vegetarian, not vegan).",
      terms: ["honig", "honey", "bienenhonig", "blutenhonig", "waldhonig", "akazienhonig", "lindenhonig"],
      termsEn: ["honey", "blossom honey", "forest honey", "acacia honey", "raw honey"],
      termsFr: ["miel", "miel de fleurs", "miel de foret", "miel d'acacia"],
      termsIt: ["miele", "miele di fiori", "miele di bosco", "miele di acacia"],
      termsEs: ["miel", "miel de flores", "miel de bosque", "miel de acacia"]
    },
    {
      status: "vegetarian",
      label: "Bee products",
      reason: "Beeswax, propolis or bee pollen - not vegan.",
      terms: ["bienenwachs", "beeswax", "propolis", "bienengift", "bienenpollen"],
      termsEn: ["beeswax", "bee wax", "propolis", "bee pollen"],
      termsFr: ["cire d'abeille", "cire d'abeilles", "propolis", "pollen d'abeille"],
      termsIt: ["cera d'api", "propoli", "polline d'api"],
      termsEs: ["cera de abeja", "propoleo", "polen de abeja"]
    },
    {
      status: "non-vegetarian",
      label: "Royal Jelly",
      reason: "Royal jelly – excluded from vegetarian certification by V-Label and the Vegetarian Society.",
      terms: ["gelee royale", "weiselfuttersaft", "koeniginnenfuttersaft"],
      termsEn: ["royal jelly"],
      termsFr: ["gelee royale"],
      termsIt: ["pappa reale"],
      termsEs: ["jalea real"]
    },
    {
      status: "vegetarian",
      label: "Lanolin",
      reason: "Wool wax - not vegan.",
      terms: ["lanolin", "wollwachs", "wollfett"],
      termsEn: ["lanolin", "wool wax", "wool fat", "anhydrous lanolin"],
      termsFr: ["lanoline", "cire de laine"],
      termsIt: ["lanolina", "cera di lana"],
      termsEs: ["lanolina", "cera de lana"]
    },
    {
      status: "conditional",
      label: "Shellac",
      reason: "From lac insects (E904) – excluded by V-Label and the Vegetarian Society as not vegetarian.",
      terms: ["schellack", "shellac"],
      termsEn: ["shellac", "lac resin", "e904"],
      termsFr: ["shellac", "gomme-laque", "laque"],
      termsIt: ["gommalacca", "lacca", "shellac"],
      termsEs: ["goma laca", "shellac", "laca"]
    },
    {
      status: "conditional",
      label: "Microbial rennet",
      reason: "No animal enzyme – usually vegan-compatible, but strict certifications may check culture media.",
      terms: ["mikrobielles lab", "mikrobielles labferment"],
      termsEn: ["microbial rennet", "vegetarian rennet", "vegetable rennet"],
      termsFr: ["presure microbienne", "presure vegetale"],
      termsIt: ["caglio microbico", "caglio vegetale"],
      termsEs: ["cuajo microbiano", "cuajo vegetal"]
    },

    /* === CONDITIONAL (may be plant-based or animal-derived) === */
    {
      status: "conditional",
      label: "Flavouring (unspecified)",
      reason: "Origin often unclear - may be plant-based or animal-derived.",
      terms: ["aroma", "aromen", "naturliches aroma", "naturliche aromen"],
      termsEn: ["flavouring", "flavorings", "flavourings", "natural flavouring", "natural flavor", "natural flavors", "natural flavourings", "artificial flavouring"],
      termsFr: ["arome", "aromes", "arome naturel", "aromes naturels"],
      termsIt: ["aroma", "aromi", "aroma naturale", "aromi naturali"],
      termsEs: ["aroma", "aromas", "aroma natural", "aromas naturales"],
      exclude: ["vanille-aroma", "vanillearoma", "vanille aroma", "zitronen-aroma", "zitronenaroma", "zitronen aroma", "frucht-aroma", "fruchtaroma", "frucht aroma", "kakao-aroma", "kakaoaroma", "kaffee-aroma", "kaffeearoma", "minz-aroma", "minzaroma", "menthol-aroma", "rum-aroma", "rumaroma", "rum aroma", "rauch-aroma", "raucharoma", "veganes aroma", "pflanzliches aroma", "vanilla flavouring", "vanilla flavor", "lemon flavour", "lemon flavor", "fruit flavour", "fruit flavor", "chocolate flavour", "coffee flavour", "mint flavour", "vegan flavouring", "arome de vanille", "arome citron", "arome fruits", "aroma vaniglia", "aroma limone", "aroma vainilla", "aroma limon"]
    },
    {
      status: "conditional",
      label: "Lecithin",
      reason: "Usually soy or sunflower, but may be egg-derived (E322).",
      terms: ["lecithin", "lezithin"],
      termsEn: ["lecithin", "e322"],
      termsFr: ["lecithine"],
      termsIt: ["lecitina"],
      termsEs: ["lecitina"],
      exclude: ["sojalecithin", "soja-lecithin", "sonnenblumenlecithin", "sonnenblumen-lecithin", "rapslecithin", "soy lecithin", "sunflower lecithin", "rapeseed lecithin", "lecithine de soja", "lecithine de tournesol", "lecitina di soia", "lecitina di girasole", "lecitina de soja", "lecitina de girasol"]
    },
    {
      status: "conditional",
      label: "Mono- and Diglycerides",
      reason: "May come from plant or animal fats (E471/E472).",
      terms: ["mono- und diglyceride", "mono und diglyceride", "monoglyceride", "diglyceride"],
      termsEn: ["mono and diglycerides", "monoglycerides", "diglycerides", "glycerides", "mono- and diglycerides of fatty acids"],
      termsFr: ["mono- et diglycerides", "monoglycerides", "diglycerides", "glycerides"],
      termsIt: ["mono e digliceridi", "monogliceridi", "digliceridi"],
      termsEs: ["mono y digliceridos", "monogliceridos", "digliceridos"]
    },
    {
      status: "conditional",
      label: "Glycerin / Glycerol",
      reason: "May be plant-based, synthetic or animal-derived (E422).",
      terms: ["glycerin", "glycerol"],
      termsEn: ["glycerin", "glycerol", "glycerine"],
      termsFr: ["glycerine", "glycerol"],
      termsIt: ["glicerina", "glicerolo"],
      termsEs: ["glicerina", "glicerol"],
      exclude: ["pflanzliches glycerin", "vegetable glycerin", "glycerine vegetale", "glicerina vegetale", "glicerina vegetal"]
    },
    {
      status: "conditional",
      label: "Enzymes",
      reason: "May be microbial, plant-based or animal-derived.",
      terms: ["enzyme", "enzymen"],
      termsEn: ["enzyme", "enzymes", "protease", "lipase", "amylase"],
      termsFr: ["enzyme", "enzymes"],
      termsIt: ["enzima", "enzimi"],
      termsEs: ["enzima", "enzimas"],
      exclude: ["mikrobielles enzym", "pflanzliches enzym", "microbial enzyme", "enzyme microbien", "enzima microbico"]
    },
    {
      status: "conditional",
      label: "Omega-3",
      reason: "May come from fish oil or algae.",
      terms: ["omega-3", "omega 3"],
      termsEn: ["omega-3", "omega 3", "dha", "epa"],
      termsFr: ["omega-3", "omega 3"],
      termsIt: ["omega-3", "omega 3"],
      termsEs: ["omega-3", "omega 3"],
      exclude: ["omega-3 aus algen", "vegan omega-3", "algal oil", "omega-3 from algae", "algae omega-3", "omega-3 d'algues", "omega-3 de algas"]
    },
    {
      status: "conditional",
      label: "Rennet / Coagulant (unspecified)",
      reason: "May be animal or microbial - check label.",
      terms: ["lab", "labaustauschstoff", "rennet"],
      termsEn: ["rennet", "coagulant"],
      termsFr: ["presure", "coagulant"],
      termsIt: ["caglio", "coagulante"],
      termsEs: ["cuajo", "coagulante"],
      exclude: ["kalberlab", "tierisches lab", "animalisches lab", "naturliches lab", "tierisches labferment", "mikrobielles labferment", "mikrobielles lab", "pflanzliches lab", "vegetarisches lab", "veganes lab", "label", "labels", "laboratorium", "labor", "animal rennet", "calf rennet", "microbial rennet", "vegetarian rennet", "presure animale", "presure microbienne", "presure vegetale", "caglio animale", "caglio microbico", "cuajo animal", "cuajo microbiano"]
    },
    {
      status: "conditional",
      label: "Fatty acids",
      reason: "May be plant-based or animal-derived.",
      terms: ["speisefettsauren", "speisefettsaeuren"],
      termsEn: ["fatty acids", "stearic acid", "palmitic acid"],
      termsFr: ["acides gras", "acide stearique", "acide palmitique"],
      termsIt: ["acidi grassi", "acido stearico", "acido palmitico"],
      termsEs: ["acidos grasos", "acido estearico", "acido palmitico"],
      exclude: ["pflanzliche speisefettsauren", "plant-based fatty acids", "vegetable fatty acids"]
    },
    {
      status: "conditional",
      label: "Taurine",
      reason: "Now mostly synthetic, but origin should be checked.",
      terms: ["taurin"],
      termsEn: ["taurine"],
      termsFr: ["taurine"],
      termsIt: ["taurina"],
      termsEs: ["taurina"]
    },
    {
      status: "conditional",
      label: "Vitamin A / Retinol",
      reason: "May be plant-based/synthetic or animal-derived.",
      terms: ["retinol", "vitamin a", "vitamin-a"],
      termsEn: ["retinol", "vitamin a", "vitamin a acetate", "vitamin a palmitate"],
      termsFr: ["retinol", "vitamine a"],
      termsIt: ["retinolo", "vitamina a"],
      termsEs: ["retinol", "vitamina a"],
      exclude: ["vitamin a aus karotten", "vegan vitamin a", "aus flechten", "aus algen"]
    },
    {
      status: "conditional",
      label: "Vitamin D3",
      reason: "Often from lanolin (sheep wool); vegan D3 from lichen possible.",
      terms: ["vitamin d3", "vitamin-d3", "cholecalciferol"],
      termsEn: ["vitamin d3", "cholecalciferol"],
      termsFr: ["vitamine d3", "cholecalciferol"],
      termsIt: ["vitamina d3", "colecalciferolo"],
      termsEs: ["vitamina d3", "colecalciferol"],
      exclude: ["vitamin d3 aus flechten", "vegan vitamin d3", "vitamin d3 aus algen", "vitamin d3 from lichen", "lichen-derived", "algae-derived vitamin d3"]
    },
    {
      status: "conditional",
      label: "Waxes (unspecified)",
      reason: "May be plant-based, mineral or animal-derived.",
      terms: ["wachs", "wachse"],
      termsEn: ["wax", "waxes", "coating"],
      termsFr: ["cire", "cires"],
      termsIt: ["cera", "cere"],
      termsEs: ["cera", "ceras"],
      exclude: ["bienenwachs", "candelillawachs", "carnaubawachs", "mikrokristallines wachs", "polyethylenwachs", "pflanzenwachs", "beeswax", "candelilla wax", "carnauba wax", "rice bran wax", "cire d'abeille", "cire de carnauba", "cire de candelilla", "cera d'api", "cera carnauba", "cera de abeja", "cera carnauba", "cera candelilla"]
    },
    {
      status: "conditional",
      label: "Worcestershire sauce",
      reason: "Traditionally contains anchovies - vegan variants available.",
      terms: ["worcestersauce", "worcestershire", "worcester"],
      termsEn: ["worcestershire sauce", "worcestershire"],
      termsFr: ["sauce worcestershire"],
      termsIt: ["salsa worcestershire"],
      termsEs: ["salsa worcestershire"],
      exclude: ["vegan worcestershire", "vegane worcestersauce"]
    },
    {
      status: "conditional",
      label: "Sugar (cane)",
      reason: "Usually fine in the EU; bone char used in some countries.",
      terms: ["rohrzucker"],
      termsEn: ["cane sugar", "raw cane sugar", "white sugar"],
      termsFr: ["sucre de canne"],
      termsIt: ["zucchero di canna"],
      termsEs: ["azucar de cana"],
      exclude: ["bio-rohrzucker", "fairtrade-rohrzucker", "organic cane sugar", "fairtrade cane sugar"]
    },
  ],

  /* ====  VEGAN KEYWORDS (completeness check)  ==== */
  veganKeywords: [
    { label: "Water",             terms: ["wasser", "aqua"],                                    termsEn: ["water"],                termsIt: ["acqua"],              termsEs: ["agua"],        termsFr: ["eau"] },
    { label: "Salt",              terms: ["salz", "meersalz", "jodsalz", "kochsalz"],           termsEn: ["salt", "sea salt", "iodised salt", "sodium chloride"], termsFr: ["sel", "sel marin", "sel iode"], termsIt: ["sale", "sale marino"], termsEs: ["sal", "sal marina"], exclude: ["natriumcaseinat"] },
    { label: "Sugar",             terms: ["zucker", "saccharose", "traubenzucker", "glukose", "glucose", "fructose", "fruktose", "maltose", "puderzucker"], termsEn: ["sugar", "sucrose", "dextrose", "glucose", "fructose", "maltose", "icing sugar", "powdered sugar"], termsFr: ["sucre", "saccharose", "dextrose", "glucose", "fructose", "maltose", "sucre glace"], termsIt: ["zucchero", "saccarosio", "destrosio", "glucosio", "fruttosio", "maltosio"], termsEs: ["azucar", "sacarosa", "dextrosa", "glucosa", "fructosa", "maltosa"], exclude: ["milchzucker", "laktose", "lactose"] },
    { label: "Flour / Grain",     terms: ["weizenmehl", "dinkelmehl", "roggenmehl", "hafermehl", "reismehl", "maismehl", "buchweizenmehl", "mehl", "vollkornmehl"], termsEn: ["wheat flour", "spelt flour", "rye flour", "oat flour", "rice flour", "corn flour", "buckwheat flour", "flour", "wholemeal flour", "semolina"], termsFr: ["farine de ble", "farine d'epeautre", "farine de seigle", "farine d'avoine", "farine de riz", "farine de mais", "farine de sarrasin", "farine", "semoule"], termsIt: ["farina di frumento", "farina di farro", "farina di segale", "farina d'avena", "farina di riso", "farina di mais", "farina", "semolino"], termsEs: ["harina de trigo", "harina de espelta", "harina de centeno", "harina de avena", "harina de arroz", "harina de maiz", "harina", "semola"] },
    { label: "Starch",            terms: ["maisstarke", "kartoffelstarke", "weizenstarke", "reisstarke", "tapiokstarke", "starke", "modifizierte starke"], termsEn: ["maize starch", "corn starch", "potato starch", "wheat starch", "rice starch", "tapioca starch", "starch", "modified starch"], termsFr: ["amidon de mais", "amidon de pomme de terre", "amidon de ble", "amidon de riz", "amidon", "amidon modifie", "fecule"], termsIt: ["amido di mais", "fecola di patate", "amido di frumento", "amido di riso", "amido", "amido modificato"], termsEs: ["almidon de maiz", "fecula de patata", "almidon de trigo", "almidon de arroz", "almidon", "almidon modificado"] },
    { label: "Plant oil",         terms: ["rapsol", "sonnenblumenol", "olivenol", "kokosnussol", "leinol", "sojaol", "maiskeimol", "palmenol", "distelol", "sesamol", "walnussol"], termsEn: ["rapeseed oil", "sunflower oil", "olive oil", "coconut oil", "linseed oil", "soybean oil", "corn oil", "palm oil", "safflower oil", "sesame oil", "walnut oil", "almond oil", "peanut oil", "avocado oil", "vegetable oil", "plant oil"], termsFr: ["huile de colza", "huile de tournesol", "huile d'olive", "huile de noix de coco", "huile de lin", "huile de soja", "huile de mais", "huile de palme", "huile de sesame", "huile vegetale"], termsIt: ["olio di colza", "olio di girasole", "olio d'oliva", "olio di cocco", "olio di semi di lino", "olio di soia", "olio di mais", "olio di palma", "olio di sesamo", "olio vegetale"], termsEs: ["aceite de colza", "aceite de girasol", "aceite de oliva", "aceite de coco", "aceite de linaza", "aceite de soja", "aceite de maiz", "aceite de palma", "aceite de sesamo", "aceite vegetal"] },
    { label: "Yeast",             terms: ["hefe", "backhefe", "trockenhefe", "hefeextrakt"],    termsEn: ["yeast", "bakers yeast", "dried yeast", "yeast extract"],         termsFr: ["levure", "levure de boulanger", "levure seche", "extrait de levure"], termsIt: ["lievito", "lievito di birra", "lievito secco", "estratto di lievito"], termsEs: ["levadura", "levadura de panaderia", "levadura seca", "extracto de levadura"] },
    { label: "Vinegar",           terms: ["essig", "apfelessig", "balsamicoessig", "weinessig"], termsEn: ["vinegar", "apple cider vinegar", "balsamic vinegar", "wine vinegar", "spirit vinegar", "white vinegar"], termsFr: ["vinaigre", "vinaigre de cidre", "vinaigre balsamique", "vinaigre de vin"], termsIt: ["aceto", "aceto di mele", "aceto balsamico", "aceto di vino"], termsEs: ["vinagre", "vinagre de manzana", "vinagre balsamico", "vinagre de vino"] },
    { label: "Cocoa / Chocolate", terms: ["kakao", "kakaopulver", "kakaobutter", "kakaomasse", "bitterschokolade"], termsEn: ["cocoa", "cocoa powder", "cocoa butter", "cocoa mass", "dark chocolate", "bittersweet chocolate"], termsFr: ["cacao", "poudre de cacao", "beurre de cacao", "masse de cacao", "chocolat noir"], termsIt: ["cacao", "polvere di cacao", "burro di cacao", "massa di cacao", "cioccolato fondente"], termsEs: ["cacao", "polvo de cacao", "manteca de cacao", "masa de cacao", "chocolate negro"] },
    { label: "Soy",               terms: ["sojaprotein", "sojaextrakt", "sojaol", "sojamehl", "sojalecithin", "tofu", "tempeh", "miso", "edamame"], termsEn: ["soy protein", "soya protein", "soy extract", "soy flour", "soy lecithin", "tofu", "tempeh", "miso", "edamame", "textured soy protein"], termsFr: ["proteine de soja", "farine de soja", "lecithine de soja", "tofu", "tempeh", "miso"], termsIt: ["proteina di soia", "farina di soia", "lecitina di soia", "tofu", "tempeh", "miso"], termsEs: ["proteina de soja", "harina de soja", "lecitina de soja", "tofu", "tempeh", "miso"] },
    { label: "Nuts / Seeds",      terms: ["mandeln", "haselnusse", "walnusse", "cashewkerne", "erdnusse", "pistazien", "pecannusse", "macadamia", "paranusse", "kokosnuss", "kokosraspeln"], termsEn: ["almonds", "hazelnuts", "walnuts", "cashews", "peanuts", "pistachios", "pecans", "macadamia", "brazil nuts", "coconut", "coconut milk", "desiccated coconut"], termsFr: ["amandes", "noisettes", "noix", "noix de cajou", "cacahuetes", "pistaches", "noix de pecan", "macadamia", "noix du bresil", "noix de coco"], termsIt: ["mandorle", "nocciole", "noci", "anacardi", "arachidi", "pistacchi", "noci pecan", "macadamia", "noci del brasile", "cocco"], termsEs: ["almendras", "avellanas", "nueces", "anacardos", "cacahuetes", "pistachos", "nueces pecanas", "macadamia", "nueces de brasil", "coco"] },
    { label: "Seeds",             terms: ["sesam", "leinsamen", "sonnenblumenkerne", "kurbiskerne", "chiasamen", "mohnsamen", "hanfsamen"], termsEn: ["sesame", "sesame seeds", "linseed", "flaxseed", "sunflower seeds", "pumpkin seeds", "chia seeds", "poppy seeds", "hemp seeds"], termsFr: ["sesame", "graines de lin", "graines de tournesol", "graines de courge", "graines de chia", "graines de pavot"], termsIt: ["sesamo", "semi di lino", "semi di girasole", "semi di zucca", "semi di chia", "semi di papavero"], termsEs: ["sesamo", "semillas de lino", "pipas de girasol", "pipas de calabaza", "semillas de chia", "semillas de amapola"] },
    { label: "Legumes",           terms: ["linsen", "kichererbsen", "erbsen", "kidneybohnen", "schwarze bohnen", "weisse bohnen", "sojabohnen", "lupinen"], termsEn: ["lentils", "chickpeas", "peas", "kidney beans", "black beans", "white beans", "soybeans", "lupins", "split peas", "fava beans", "broad beans"], termsFr: ["lentilles", "pois chiches", "petits pois", "haricots rouges", "haricots noirs", "haricots blancs", "soja", "lupin"], termsIt: ["lenticchie", "ceci", "piselli", "fagioli borlotti", "fagioli neri", "fagioli bianchi", "soia", "lupini"], termsEs: ["lentejas", "garbanzos", "guisantes", "judias rojas", "alubias negras", "judias blancas", "soja", "altramuces"] },
    { label: "Vegetables",        terms: ["tomaten", "karotten", "mohren", "spinat", "brokkoli", "paprika", "zucchini", "aubergine", "mais", "erbsen", "zwiebeln", "knoblauch", "ingwer", "sellerie", "lauch", "fenchel"], termsEn: ["tomatoes", "tomato paste", "carrots", "spinach", "broccoli", "peppers", "courgette", "zucchini", "aubergine", "eggplant", "corn", "sweetcorn", "peas", "onions", "garlic", "ginger", "beetroot", "celery", "leek", "fennel", "sweet potato", "kale", "cauliflower"], termsFr: ["tomates", "carottes", "epinards", "brocoli", "poivrons", "courgette", "aubergine", "mais", "petits pois", "oignons", "ail", "gingembre", "betterave", "celeri", "poireau", "fenouil"], termsIt: ["pomodori", "carote", "spinaci", "broccoli", "peperoni", "zucchine", "melanzane", "mais", "piselli", "cipolle", "aglio", "zenzero", "sedano", "porro", "finocchio"], termsEs: ["tomates", "zanahorias", "espinacas", "brocoli", "pimientos", "calabacin", "berenjena", "maiz", "guisantes", "cebollas", "ajo", "jengibre", "apio", "puerro", "hinojo"] },
    { label: "Fruit",             terms: ["apfel", "orangen", "zitronen", "limetten", "bananen", "erdbeeren", "himbeeren", "heidelbeeren", "rosinen", "datteln", "feigen", "mango", "ananas"], termsEn: ["apples", "oranges", "lemons", "limes", "bananas", "strawberries", "raspberries", "blueberries", "raisins", "dates", "figs", "mango", "pineapple", "grapes", "cherries", "peaches", "plums", "apricots"], termsFr: ["pommes", "oranges", "citrons", "limes", "bananes", "fraises", "framboises", "myrtilles", "raisins secs", "dattes", "figues", "mangue", "ananas", "cerises"], termsIt: ["mele", "arance", "limoni", "lime", "banane", "fragole", "lamponi", "mirtilli", "uva passa", "datteri", "fichi", "mango", "ananas", "ciliegie"], termsEs: ["manzanas", "naranjas", "limones", "limas", "platanos", "fresas", "frambuesas", "arandanos", "pasas", "datiles", "higos", "mango", "pina", "cerezas"] },
    { label: "Fruit juice",       terms: ["apfelsaft", "orangensaft", "zitronensaft", "fruchtsaft", "fruchtmark", "fruchtpuree", "konzentrat"], termsEn: ["apple juice", "orange juice", "lemon juice", "fruit juice", "fruit puree", "fruit concentrate", "juice concentrate"], termsFr: ["jus de pomme", "jus d'orange", "jus de citron", "jus de fruits", "puree de fruits", "concentre de jus"], termsIt: ["succo di mela", "succo d'arancia", "succo di limone", "succo di frutta", "purea di frutta", "concentrato di succo"], termsEs: ["zumo de manzana", "zumo de naranja", "zumo de limon", "zumo de frutas", "pure de frutas", "concentrado de zumo"] },
    { label: "Cereals / Flakes",  terms: ["haferflocken", "cornflakes", "reisflocken", "quinoa", "amaranth", "hirse", "buchweizen", "dinkel", "roggen", "hafer"], termsEn: ["oats", "oat flakes", "cornflakes", "rice flakes", "quinoa", "amaranth", "millet", "buckwheat", "spelt", "rye", "barley", "wheat flakes"], termsFr: ["flocons d'avoine", "flocons de mais", "cornflakes", "flocons de riz", "quinoa", "amarante", "millet", "sarrasin", "epeautre", "seigle"], termsIt: ["fiocchi d'avena", "corn flakes", "fiocchi di riso", "quinoa", "amaranto", "miglio", "grano saraceno", "farro", "segale"], termsEs: ["copos de avena", "cornflakes", "copos de arroz", "quinoa", "amaranto", "mijo", "trigo sarraceno", "espelta", "centeno"] },
    { label: "Spices / Herbs",    terms: ["gewurze", "krauter", "gewurzmischung", "krutermischung"], termsEn: ["spices", "herbs", "mixed spices", "mixed herbs", "seasoning", "herb mix"], termsFr: ["epices", "herbes", "melange d'epices", "melange d'herbes", "assaisonnement"], termsIt: ["spezie", "erbe", "miscela di spezie", "miscela di erbe", "condimento"], termsEs: ["especias", "hierbas", "mezcla de especias", "mezcla de hierbas", "condimento"] },
    { label: "Individual spices", terms: ["pfeffer", "paprika", "kurkuma", "zimt", "ingwer", "chili", "cayenne", "oregano", "basilikum", "thymian", "rosmarin", "koriander", "kreuzkummel", "muskat", "lorbeer", "kardamom", "anis", "curry", "safran", "vanille"], termsEn: ["pepper", "paprika", "turmeric", "cinnamon", "ginger", "chilli", "chili", "cayenne", "oregano", "basil", "thyme", "rosemary", "coriander", "cumin", "nutmeg", "bay leaf", "cardamom", "anise", "fennel seeds", "fenugreek", "curry", "saffron", "vanilla"], termsFr: ["poivre", "paprika", "curcuma", "cannelle", "gingembre", "piment", "cayenne", "origan", "basilic", "thym", "romarin", "coriandre", "cumin", "muscade", "laurier", "cardamome", "anis", "fenouil", "fenugrec", "curry", "safran", "vanille"], termsIt: ["pepe", "paprica", "curcuma", "cannella", "zenzero", "peperoncino", "cayenna", "origano", "basilico", "timo", "rosmarino", "coriandolo", "cumino", "noce moscata", "alloro", "cardamomo", "anice", "finocchio", "fieno greco", "curry", "zafferano", "vaniglia"], termsEs: ["pimienta", "pimenton", "curcuma", "canela", "jengibre", "chile", "cayena", "oregano", "albahaca", "tomillo", "romero", "cilantro", "comino", "nuez moscada", "laurel", "cardamomo", "anis", "hinojo", "fenogreco", "curry", "azafran", "vainilla"] },
    { label: "Plant sweeteners",  terms: ["agavendicksaft", "agavensirup", "ahornsirup", "reissirup", "dattelsirup", "kokosblutenzucker", "stevia", "xylit", "erythrit"], termsEn: ["agave syrup", "agave nectar", "maple syrup", "rice syrup", "date syrup", "coconut sugar", "stevia", "xylitol", "erythritol"], termsFr: ["sirop d'agave", "sirop d'erable", "sirop de riz", "sirop de dattes", "sucre de coco", "stevia", "xylitol", "erythritol"], termsIt: ["sciroppo d'agave", "sciroppo d'acero", "sciroppo di riso", "sciroppo di datteri", "zucchero di cocco", "stevia", "xilitolo", "eritritolo"], termsEs: ["jarabe de agave", "sirope de agave", "jarabe de arce", "sirope de arroz", "jarabe de datil", "azucar de coco", "stevia", "xilitol", "eritritol"] },
    { label: "Maltodextrin",      terms: ["maltodextrin", "dextrose", "glukosesirup", "fruktosesirup"], termsEn: ["maltodextrin", "dextrose", "glucose syrup", "fructose syrup"], termsFr: ["maltodextrine", "dextrose", "sirop de glucose", "sirop de fructose"], termsIt: ["maltodestrina", "destrosio", "sciroppo di glucosio", "sciroppo di fruttosio"], termsEs: ["maltodextrina", "dextrosa", "jarabe de glucosa", "jarabe de fructosa"] },
    { label: "Coffee / Tea",      terms: ["kaffee", "kaffeeextrakt", "espresso", "tee", "gruner tee", "matcha", "rooibos"], termsEn: ["coffee", "coffee extract", "espresso", "tea", "green tea", "matcha", "rooibos", "black tea", "herbal tea"], termsFr: ["cafe", "extrait de cafe", "espresso", "the", "the vert", "matcha", "rooibos", "the noir", "tisane"], termsIt: ["caffe", "estratto di caffe", "espresso", "te", "te verde", "matcha", "rooibos", "te nero", "tisana"], termsEs: ["cafe", "extracto de cafe", "espresso", "te", "te verde", "matcha", "rooibos", "te negro", "infusion"] },
  ]
};
